### ISSUE TITLE
how to repair the database

### ISSUE THREAD

**Issue by ghost** [leafnote/leafnote#4]

**Comment by ghost** [comment]
as it wont load the browser flipnotes menu

**Comment by ghost** [comment]
Unhandled Error
Traceback (most recent call last):
  File "server.py", line 146, in <module>
    reactor.run()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1283, in run
    self.mainLoop()
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 1292, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\base.py", line 913, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "C:\Users\purpe\Desktop\leafnote-master\hatenadir\ds\v2-xx\ch\pokemon.ugo.py", line 35, in Update
    if self.newestflip <> Database.Newest[0]:
exceptions.IndexError: list index out of range


and it will spam this error the whole time
